### ISSUE TITLE
Eslint support

### ISSUE THREAD

**Issue by zomars** [bobdenotter/symfony-skeleton#10]
Is it too early to add [eslint support](https://alligator.io/vuejs/vue-eslint-plugin/)?

**Comment by bobdenotter** [comment]
Not at all. Free free to add it in, if you will :-)

**Comment by xiaohutai** [comment]
👍 

Maybe add https://prettier.io/ too?

See also:
- https://prettier.io/docs/en/eslint.html
- https://prettier.io/docs/en/comparison.html
- Github: https://github.com/prettier/prettier (seems quite popular; not an objective measure of it being good but still)

**Comment by zomars** [comment]
@xiaohutai I use both actually in a boilerplate that I'm working with

**Comment by zomars** [comment]
Let me figure a propper configuration

**Comment by zomars** [comment]
It's alive! 

![image](https://user-images.githubusercontent.com/3504472/46751621-4f194c80-cc78-11e8-958b-ff1738267a64.png)
